version: '3.8'

services:
  mongo:
    image: docker.io/library/mongo
    ports:
      - 3456:27017
    env_file:
      - .env
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      # - mongo_data:/data/db
  redis:
    image: docker.io/library/redis
    ports:
      - 6379:6379
# volumes:
#   mongo_data:

