version: '3.8'

services:
  mongo:
    image: docker.io/library/mongo
    ports:
      - 3456:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    #   - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - .env
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      # 1
      # - ./mongo_data:/data/db 
      # 2
      # - mongo_data:/data/db
  redis:
    image: docker.io/library/redis
    ports:
      - 6379:6379
# 2
# volumes:
#   mongo_data:

